name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      # Playwright / Web
      BASE_API: ${{ secrets.BASE_API }}
      BASE_URL: ${{ secrets.BASE_URL }}

      # API - App
      env:
      CI: true
      PORT: 3333
      NODE_ENV: test
      DB_DIALECT: postgres

      # API - Database (MAPEADO DUPLO PARA EVITAR ERRO DE SENHA)
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PORT: ${{ secrets.DB_PORT }}

      DB_PASS: ${{ secrets.DB_PASSWORD }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      DB_NAME: ${{ secrets.DB_DATABASE }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}

      # Auth
      ADMIN_USER: ${{ secrets.ADMIN_USER }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
      ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
      ADMIN_ID: ${{ secrets.ADMIN_ID }}

    steps:
      # Repo de testes Playwright
      - name: Checkout Playwright repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Monorepo ZombiePlus (API + Web)
      - name: Checkout ZombiePlus (API + Web)
        uses: actions/checkout@v4
        with:
          repository: caamilatavares/zombieplus-package
          ref: main
          path: zombieplus

      - name: Remove .env files
        run: rm -f .env .env.test

      # API
      - name: Install API dependencies
        working-directory: zombieplus/api
        run: npm install

      - name: Start API
        working-directory: zombieplus/api
        run: npm run start:ci &

      # Web
      - name: Install Web dependencies
        working-directory: zombieplus/web
        run: npm install

      - name: Start Web
        working-directory: zombieplus/web
        run: npm run start:ci &

      # Wait services
      - name: Wait for API
        run: npx wait-on http://localhost:3333 --timeout 30000

      - name: Wait for Web
        run: npx wait-on http://localhost:3000 --timeout 30000

      # Playwright
      - name: Install test dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
