name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Playwright repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Checkout ZombiePlus (API + Web)
        uses: actions/checkout@v4
        with:
          repository: caamilatavares/zombieplus-package
          ref: main
          path: zombieplus

      # API.
      - name: Install API dependencies
        working-directory: zombieplus/api
        run: npm install

      - name: Start API
        working-directory: zombieplus/api
        run: npm run start &

      # Web
      - name: Install Web dependencies
        working-directory: zombieplus/web
        run: npm install

      - name: Start Web
        working-directory: zombieplus/web
        run: npm run dev &

      # Wait services
      - name: Wait for API
        run: npx wait-on http://localhost:3333

      - name: Wait for Web
        run: npx wait-on http://localhost:3000

      # Playwright
      - name: Install test dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
